networks:
  dev-internal:

volumes:
  opensearch-volume:

services:
  opensearch:
    image: docker.io/opensearchproject/opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms128m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=OpenSearch#0
      - plugins.security.ssl.http.enabled=false
    volumes:
      - opensearch-volume:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: curl -k -s --fail -u admin:OpenSearch#0 http://localhost:9200/_cluster/health || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - dev-internal
